server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.learn.minecraftmap: DEBUG
